print("run in PYTHON3")
p1 = input("Person1")
p1_gpa = float(input("Person1's gpa"))
p2 = input("Person2")
p2_gpa = float(input("Person2's gpa"))
p3 = input("Person3")
p3_gpa = float(input("Person3's gpa"))
p4 = input("Person4")
p4_gpa = float(input("Person4's gpa"))

gpa_average = ((p1_gpa + p2_gpa + p3_gpa + p4_gpa) / 4)
print(p1, p2, p3, p4, gpa_average)